name: comment-on-pr
on: pull_request
jobs:
  comment-on-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Comment
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Just commenting on PR!"
